# Generated by Django 5.2.11 on 2026-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Logia')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('fundacion', models.IntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripción')),
                ('bandera', models.CharField(default='🏛️', max_length=10, verbose_name='Bandera/Emoji')),
                ('categoria', models.CharField(choices=[('mundo', '🌍 Logias del Mundo'), ('mexico', '🇲🇽 Logias de México'), ('yucatan', '🌴 Logias de Yucatán')], max_length=20, verbose_name='Categoría')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logia',
                'verbose_name_plural': 'Logias',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
