# Generated by Django 5.2.11 on 2026-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_logia'),
    ]

    operations = [
        migrations.AddField(
            model_name='principio',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
