# Generated by Django 5.2.11 on 2026-02-12 19:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
